version: '3.1'

services:
  fuseadmin:
    build: image
    container_name: fuseadmin
    ports:
      - "8181:8181"
      - "8101:8101"
      - "9000:9000"
    environment:
      - FUSE_KARAF_NAME=fuseadmin
      - FABRIC_USER=admin
      - FABRIC_PASSWD=admin
      - ZOOKEEPER_PASSWD=admin
  fuseroot1:
    build: image
    container_name: fuseroot1
    ports:
       - "8182:8181"
       - "8102:8101"
    environment:
      - FUSE_KARAF_NAME=fuseroot1
    entrypoint: /opt/jboss/jboss-fuse/bin/fabric-join.sh